signup/core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.SurveyListView.as_view(), name='survey_list'),
    path('survey/create/', views.SurveyCreateView.as_view(), name='survey_create'),
    path('survey/update/<int:pk>', views.SurveyUpdateView.as_view(), name='survey_update'),
    path('survey/detail/<int:pk>', views.SurveyDetailView.as_view(), name='survey_detail'),
    path('survey/delete/<int:pk>', views.SurveyDeleteView.as_view(), name='survey_delete'),

    path('question/create/<int:surv_id>', views.QuestionCreateView.as_view(), name='question_create'),
    path('question/list/<int:surv_id>/', views.QuestionListView.as_view(), name='question_list'),
    path('question/update/<int:pk>', views.QuestionUpdateView.as_view(), name='question_update'),
    path('question/delete/<int:pk>', views.QuestionDeleteView.as_view(), name='question_delete'),

    path('submission/list/', views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/list/aggregate/<int:surv_id>/', views.SubmissionListViewAggregate.as_view(), name='submission_list_aggregate'),
    path('submission/create/<int:surv_id>/', views.submission_create, name='submission_create'),
    path('submission/detail/<slug:slug>', views.submission_detail, name='submission_detail'),
]

signup/signup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

signup/core/models.py
from django.db import models
from django.utils import timezone

survey_description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'

class Survey(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=2550, default=survey_description)
    def __str__(self):
        return self.title

class Question(models.Model):
    TEXT = "text"
    SHORT_TEXT = "short-text"
    QUESTION_TYPES = (
        (TEXT, "text (multiple line)"),
        (SHORT_TEXT, "short text (one line)"),
    )
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, null=True,  editable=True)
    type = models.CharField(max_length=255, choices=QUESTION_TYPES, default='TextField')
    text = models.TextField(max_length=2550)
    def __str__(self):
        return self.text

class Submission(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False, editable=False)
    answer = models.TextField(max_length=2550)
    slug = models.SlugField(editable=False)
    created_at = models.DateTimeField(editable=False, default=timezone.now)
    updated_at = models.DateTimeField(editable=False, default=timezone.now)
    def __str__(self):
        return self.slug

signup/core/forms.py
from random import choices
from django import forms
from core import models
from django.forms import inlineformset_factory, modelformset_factory
from bootstrap_modal_forms.forms import BSModalModelForm

class SurveyForm(BSModalModelForm):
    class Meta:
        model = models.Survey
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(SurveyForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['type'] = 'text'
            visible.field.widget.attrs['placeholder'] = 'Placeholder'

class QuestionForm(BSModalModelForm):
    class Meta:
        model = models.Question
        fields = '__all__'

FIELDS = {
    models.Question.TEXT: forms.CharField,
    models.Question.SHORT_TEXT: forms.CharField,
}
WIDGETS = {
    models.Question.TEXT: forms.Textarea,
    models.Question.SHORT_TEXT: forms.TextInput,
}

class SubmissionForm(forms.ModelForm):
    class Meta:
        model = models.Submission
        fields = '__all__'
    def get_question_widget(self, question):
        """Return the widget we should use for a question.
        :param Question question: The question
        :rtype: django.forms.widget or None"""
        try:
            return self.WIDGETS[question.type]
        except KeyError:
            return None

signup/core/views.py
from urllib import request
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse, reverse_lazy

from django.forms import inlineformset_factory, modelformset_factory, formset_factory
from django.shortcuts import render

from core import models
from core import forms

import uuid

from bootstrap_modal_forms.generic import BSModalReadView, BSModalCreateView, BSModalDeleteView, BSModalFormView, BSModalUpdateView

from django.db.models import Count
from django_pivot.pivot import pivot
from django_pivot.histogram import histogram

redirect_view = 'survey_list'

#############
#############
#############
class SurveyListView(ListView):
    model = models.Survey
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question_list'] = models.Question.objects.all()
        return context

class SurveyCreateView(BSModalCreateView):
    template_name = 'core/survey_create.html'
    form_class = forms.SurveyForm
    model = models.Survey
    success_message = 'Success: survey was created.'
    success_url = reverse_lazy(redirect_view)

class SurveyUpdateView(BSModalUpdateView):
    template_name = 'core/survey_update.html'
    form_class = forms.SurveyForm
    model = models.Survey
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy(redirect_view)

class SurveyDeleteView(BSModalDeleteView):
    template_name = 'core/survey_delete.html'
    model = models.Survey
    success_message = 'Approach successfully deleted.'
    success_url = reverse_lazy(redirect_view)

class SurveyDetailView(DetailView):
    template_name = 'core/survey_detail.html'
    model = models.Survey

#############
#############
#############
class QuestionCreateView(BSModalCreateView):
    template_name = 'core/question_create.html'
    form_class = forms.QuestionForm
    model = models.Question
    success_message = 'Success: question was created.'
    success_url = reverse_lazy(redirect_view)
    def get_initial(self):
        initial = super(QuestionCreateView, self).get_initial()
        surv_id = self.kwargs.get('surv_id')
        initial['survey'] = surv_id
        return initial

class QuestionListView(ListView):
    model = models.Question
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        surv_id = self.kwargs.get('surv_id')
        context['question_list'] = models.Question.objects.filter(survey_id=surv_id)
        return context

class QuestionUpdateView(BSModalUpdateView):
    template_name = 'core/question_update.html'
    model = models.Question
    form_class = forms.QuestionForm
    success_url = reverse_lazy(redirect_view)

class QuestionDeleteView(DeleteView):
    template_name = 'core/question_delete.html'
    model = models.Question
    fields = '__all__'
    success_url = reverse_lazy(redirect_view)

#############
#############
#############
class SubmissionListView(ListView):
    model = models.Submission
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['survey_list'] = models.Survey.objects.all()
        context['question_list'] = models.Question.objects.all()
        set = models.Submission.objects.all().values('question__survey__title').annotate(count=Count('slug', distinct=True))
        print(set)
        context['set_list'] = set
        return context

class SubmissionListViewAggregate(ListView):
    model = models.Submission
    template_name = 'core/submission_list_aggregate.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        surv_id = self.kwargs.get('surv_id')
        set = models.Submission.objects.all().values('question__survey__title').annotate(count=Count('slug', distinct=True))
        survey_set = models.Submission.objects.filter(question__survey__id=surv_id)

        survery_set_distinct = models.Submission.objects.filter(question__survey__id=surv_id).values('slug').distinct()
        survery_set_distinct_name = models.Survey.objects.filter(id=surv_id).values('title').distinct()

        context['survery_set_distinct'] = survery_set_distinct
        context['survery_set_distinct_name'] = survery_set_distinct_name

        context['survey_list'] = models.Survey.objects.all()
        context['question_list'] = models.Question.objects.all()
        context['set_list'] = set
        context['survey_set_list'] = survey_set
        return context

def submission_detail(request, slug):
    submission = models.Submission.objects.filter(slug=slug)
    context = {
        'submission': submission,
    }
    return render(request, 'core/submission_detail.html', context)

def submission_create(request, surv_id):
    questions = models.Question.objects.filter(survey_id=surv_id)
    SubmissionFormSet = modelformset_factory(models.Submission, form=forms.SubmissionForm, extra=questions.count())
    initial_values = [{'question': id} for id in questions.values_list('pk', flat=True)]
    formset = SubmissionFormSet(queryset=models.Submission.objects.none(), initial=initial_values)
    question_pk = questions.values_list('pk', flat=True)
    question_text = questions.values_list('text', flat=True)
    question_type = questions.values_list('type', flat=True)
    hash = uuid.uuid4().hex
    if request.method == 'POST':
        formset = SubmissionFormSet(request.POST)
        if formset.is_valid():
            index = 0
            for form in formset:
                question_id = question_pk[index]
                question = models.Question.objects.get(id=question_id)
                form.instance.hash = hash
                form.instance.slug = hash
                form.instance.question = question
                form.save()
                index += 1
            return render(request, 'core/submission_list.html')
    context = {
        'question_text': question_text,
        'question_type': question_type,
        'formset': formset,
    }
    return render(request, 'core/submission_create.html', context)

signup/core/templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
	<meta name="generator" content="Hugo 0.98.0">
	<title></title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">
	
	<div class="modal fade" tabindex="-1" role="dialog" id="modal">
		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content"></div>
		</div>
	</div>
	
	<div class="container py-3">
		<header>
			<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
				<a href="/" class="d-flex align-items-center text-dark text-decoration-none">
					<svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
					<span class="fs-4">Pricing example</span>
				</a>
				<nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
					<a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'survey_list' %}">Surveys</a>
					<a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'submission_list' %}">Submissions</a>
				</nav>
				<a class="btn btn-outline-primary" href="#">Sign up</a>
			</div>
			
		</header>
		
		<div class="vh-100">
			<main>
				{% block content %}{% endblock content %}
			</main>
		</div>
		
		<footer class="pt-4 my-md-5 pt-md-5 border-top">
			<div class="row">
				<div class="col-12 col-md">
					<img class="mb-2" src="{% static 'assets/bootstrap-logo.svg' %}" alt="" width="24" height="19">
					<small class="d-block mb-3 text-muted">&copy; 2017–2022</small>
				</div>
				<div class="col-6 col-md">
					<h5>Features</h5>
					<ul class="list-unstyled text-small">
						<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
					</ul>
				</div>
				<div class="col-6 col-md">
					<h5>Resources</h5>
					<ul class="list-unstyled text-small">
						<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
					</ul>
				</div>
				<div class="col-6 col-md">
					<h5>About</h5>
					<ul class="list-unstyled text-small">
						<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
					</ul>
				</div>
			</div>
		</footer>
		
	</div>
	
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
	
	<script type="text/javascript">
	$(function () {
		$("#survey-create").modalForm({
			formURL: "{% url 'survey_create' %}"
		});

		$(".survey-read").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});
		
		$(".survey-delete").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
		
		var asyncSuccessMessage = [
		"<div ",
		"style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
		"class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
		"Success: Approach was updated.",
		"<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
		"<span aria-hidden='true'>&times;</span>",
		"</button>",
		"</div>",
		"<script>",
			"$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
			"<\/script>"
			].join("");
			
			function updateSurveyModalForm() {
				$(".survey-update").each(function () {
					$(this).modalForm({
						formURL: $(this).data("form-url"),
						asyncUpdate: true,
						asyncSettings: {
							closeOnSubmit: true,
							successMessage: asyncSuccessMessage,
							dataUrl: "tables/",
							dataElementId: "#survey",
							dataKey: "table",
							addModalFormFunction: updateSurveyModalForm
						}
					});
				});
			}
			updateSurveyModalForm();
			
			// Read and Delete person buttons open modal with id="modal"
			// The formURL is retrieved from the data of the element
			$(".bs-modal").each(function () {
				$(this).modalForm({formURL: $(this).data("form-url")});
			});
			
			// Hide message
			$(".alert").fadeTo(2000, 500).slideUp(500, function () {
				$(".alert").slideUp(500);
			});
		});
	</script>

</body>
</html>

signup/core/templates/core/question_create.html
<form method="post" action="">
    {% csrf_token %}
    
    <div class="modal-header">
        <h3 class="modal-title">Add Question</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    <div class="modal-body">
        <p>Add a <strong>new question</strong></p>
        {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
    
</form>

signup/core/templates/core/question_delete.html
<form method="post" action="">
    {% csrf_token %}
    
    <div class="modal-header">
        <h3 class="modal-title">Delete Survey</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    <div class="modal-body">
        <p>Are you sure that you want to delete <strong>{{ survey.title }}</strong>?</p>
    </div>
    
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
    </div>
    
</form>

signup/core/templates/core/question_list.html
{% extends 'core/base.html' %}

{% block content %}

<h2 class="display-6 text-center mb-4">Questions</h2>

<ul>
    {% for question in question_list %}
    <li>
        {{ question.text }} |
        <a href="{% url 'question_delete' question.pk %}">delete</a>
    </li>
    {% endfor %}
</ul>

{% endblock content %}

signup/core/templates/core/question_update.html
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}
    
    <div class="modal-header">
        <h3 class="modal-title">Update Question</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    <div class="modal-body">
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.label %}
            <div class="{% if field.errors %} invalid{% endif %}">
                {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
    
</form>

signup/core/templates/core/submission.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title></title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/checkout/">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/submission.css' %}" rel="stylesheet">
</head>
<body class="bg-light">
    
    <div class="container">
        <main>
            <div class="py-5 text-center">
                <h2>Submission</h2>
                <p class="lead">Some paragraph text</p>
            </div>
            
            <div class="row g-5">
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Billing address</h4>
                    <form class="needs-validation" novalidate>
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="firstName" class="form-label">First name</label>
                                <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>
                            
                            <div class="col-sm-6">
                                <label for="lastName" class="form-label">Last name</label>
                                <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>
                            
                            <div class="col-12">
                                <label for="username" class="form-label">Username</label>
                                <div class="input-group has-validation">
                                    <span class="input-group-text">@</span>
                                    <input type="text" class="form-control" id="username" placeholder="Username" required>
                                    <div class="invalid-feedback">
                                        Your username is required.
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-12">
                                <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                                <input type="email" class="form-control" id="email" placeholder="you@example.com">
                                <div class="invalid-feedback">
                                    Please enter a valid email address for shipping updates.
                                </div>
                            </div>
                            
                            <div class="col-12">
                                <label for="address" class="form-label">Address</label>
                                <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
                                <div class="invalid-feedback">
                                    Please enter your shipping address.
                                </div>
                            </div>
                            
                            <div class="col-12">
                                <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
                                <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
                            </div>
                            
                            <div class="col-md-5">
                                <label for="country" class="form-label">Country</label>
                                <select class="form-select" id="country" required>
                                    <option value="">Choose...</option>
                                    <option>United States</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please select a valid country.
                                </div>
                            </div>
                            
                            <div class="col-md-4">
                                <label for="state" class="form-label">State</label>
                                <select class="form-select" id="state" required>
                                    <option value="">Choose...</option>
                                    <option>California</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please provide a valid state.
                                </div>
                            </div>
                            
                            <div class="col-md-3">
                                <label for="zip" class="form-label">Zip</label>
                                <input type="text" class="form-control" id="zip" placeholder="" required>
                                <div class="invalid-feedback">
                                    Zip code required.
                                </div>
                            </div>
                        </div>
                        
                        <hr class="my-4">
                        
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="same-address">
                            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
                        </div>
                        
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="save-info">
                            <label class="form-check-label" for="save-info">Save this information for next time</label>
                        </div>
                        
                        <hr class="my-4">
                        
                        <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>

                    </form>
                </div>
            </div>
        </main>
        
        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2017–2022 Company Name</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
        </footer>
    </div>
    
</body>
</html>

signup/core/templates/core/survey_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<h2 class="display-6 text-center mb-4">Survey: {{ survey.title }} {{ survey.pk }}</h2>

<div class="list-group">
    {% for question in survey.question_set.all %}
    <button type="button" class="survey-update bs-modal list-group-item list-group-item-action" data-form-url="{% url 'question_update' question.pk %}">
        <div class="d-flex w-100 justify-content-between">
            <small class="text-muted">{{ question.type }}</small>
        </div>
        <p class="mb-1">{{ question.text }}</p>
    </button>
    {% endfor %}
</div>

<div class="list-group mt-4">
    <button type="button" class="survey-update bs-modal list-group-item list-group-item-action active" data-form-url="{% url 'survey_update' survey.pk %}">Survey update</button>
    <button type="button" class="survey-delete bs-modal list-group-item list-group-item-action active" data-form-url="{% url 'survey_delete' survey.pk %}">Survey delete</button>
</div>

<div class="list-group mt-4">
    <button id="question-create" class="list-group-item list-group-item-action active" type="button" name="button">Question add</button>
</div>

<div class="list-group mt-4">
    <a href="{% url 'submission_create' survey.pk %}" class="list-group-item list-group-item-action active">Submission add</a>
    <a href="{% url 'submission_list_aggregate' survey.pk %}" class="list-group-item list-group-item-action active">Submission list</a>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

<script type="text/javascript">
$(function () {
    $("#survey-create").modalForm({
        formURL: "{% url 'survey_create' %}"
    });

    $("#question-create").modalForm({
        formURL: "{% url 'question_create' survey.pk %}"
    });

    $(".survey-read").each(function () {
        $(this).modalForm({formURL: $(this).data("form-url")});
    });
    
    $(".survey-delete").each(function () {
        $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
    });
    
    var asyncSuccessMessage = [
    "<div ",
    "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
    "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
    "Success: Approach was updated.",
    "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
    "<span aria-hidden='true'>&times;</span>",
    "</button>",
    "</div>",
    "<script>",
        "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
        "<\/script>"
        ].join("");
        
        function updateSurveyModalForm() {
            $(".survey-update").each(function () {
                $(this).modalForm({
                    formURL: $(this).data("form-url"),
                    asyncUpdate: true,
                    asyncSettings: {
                        closeOnSubmit: true,
                        successMessage: asyncSuccessMessage,
                        dataUrl: "tables/",
                        dataElementId: "#survey",
                        dataKey: "table",
                        addModalFormFunction: updateSurveyModalForm
                    }
                });
            });
        }
        updateSurveyModalForm();
        
        // Read and Delete person buttons open modal with id="modal"
        // The formURL is retrieved from the data of the element
        $(".bs-modal").each(function () {
            $(this).modalForm({formURL: $(this).data("form-url")});
        });
        
        // Hide message
        $(".alert").fadeTo(2000, 500).slideUp(500, function () {
            $(".alert").slideUp(500);
        });
    });
</script>

{% endblock content %}

signup/core/templates/core/survey_list.html
{% extends 'core/base.html' %}

{% block content %}

<h2 class="display-6 text-center mb-4">Surveys</h2>

<div class="list-group mb-4">
    {% for survey in survey_list %}
    <a href="{% url 'survey_detail' survey.pk %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ survey.title }}</h5>
            <small class="text-muted">questions: {{ survey.question_set.count }}</small>
        </div>
        <p class="mb-1">Subtitle</p>
        <small class="text-muted">{{ survey.description }}</small>
        <span class="badge bg-secondary rounded-pill">{{ survey.question.submission_set.count }}</span>
    </a>
    {% endfor %}
</div>

<div class="list-group mb-4">
    <button id="survey-create" class="list-group-item list-group-item-action active" type="button" name="button">Survey add</button>
</div>

{% endblock content %}